FROM protocol:1.0.1
MAINTAINER "Jacky123"

WORKDIR /usr/wic-go
RUN go env -w GO111MODULE=on
RUN go env -w GOPROXY=https://proxy.golang.org,direct
ADD . /usr/wic-go
COPY ./conf/app-http.conf /usr/wic-go/conf/app.conf
RUN go mod download
RUN go build main.go

RUN ln -sf /usr/share/zoneinfo/Asia/Shanghai /etc/localtime

EXPOSE 8005
# 启动时执行go
ENTRYPOINT ["./main"]